# Generated by Django 5.1.3 on 2024-12-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.JSONField(default=list),
        ),
    ]
