# Generated by Django 5.1.3 on 2024-12-07 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the machine learning model', max_length=255)),
                ('description', models.TextField(help_text='Description of the model')),
                ('model_file', models.FileField(help_text='Path to the uploaded model file', upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of model creation')),
                ('model_type', models.CharField(help_text='Type of the model (e.g., image segmentation, object detection)', max_length=50)),
                ('model_image', models.ImageField(blank=True, help_text='Image of the model', null=True, upload_to='model_images/')),
                ('allowed_xai_models', models.JSONField(default=list, help_text='List of allowed XAI models for this model')),
                ('classes', models.JSONField(default=list, help_text='List of allowed target classes for the model')),
                ('allowed_users', models.JSONField(default=list, help_text='List of allowed user types for this model')),
                ('created_by', models.ForeignKey(help_text='Admin who uploaded the model', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pipeline Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
