# Generated by Django 5.1.3 on 2024-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='allowed_models',
            field=models.JSONField(default=list),
        ),
    ]
