# Generated by Django 5.1.3 on 2024-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_pipeline_allowed_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='allowed_users',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed user types for this model', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='allowed_xai_models',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed XAI models for this model', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='classes',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed target classes for the model', null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_file',
            field=models.FileField(help_text='Path to the uploaded model file', upload_to='models_weights/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('ImageSegmentation', 'Image Segmentation'), ('ObjectDetection', 'Object Detection')], help_text='Type of the model (e.g., image segmentation, object detection)', max_length=50),
        ),
    ]
