# Generated by Django 5.1.3 on 2024-12-17 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_model_allowed_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_image', models.ImageField(blank=True, null=True, upload_to='test_images/', verbose_name='Test Image')),
                ('video_feed_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Video Feed URL')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.model', verbose_name='Model')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.pipeline', verbose_name='Pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(help_text='Generated report file (PDF, etc.)', upload_to='reports/')),
                ('xai_visualization', models.ImageField(blank=True, help_text='XAI visual representation (e.g., saliency map)', null=True, upload_to='xai_visualizations/')),
                ('bounding_boxes', models.JSONField(blank=True, help_text='Coordinates of bounding boxes for object detection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.testcase', verbose_name='Test Case')),
            ],
        ),
    ]
