# Generated by Django 5.1.3 on 2024-12-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_testcase_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('ImageSegmentation', 'Image Segmentation'), ('ObjectDetection', 'Object Detection'), ('HumanDetection', 'Human Detection')], help_text='Type of the model (e.g., image segmentation, object detection)', max_length=50),
        ),
    ]
