# Generated by Django 5.2.2 on 2025-07-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_model_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='xai_algo',
            field=models.CharField(blank=True, choices=[('gradcam', 'Grad‑CAM'), ('scorecam', 'Score‑CAM'), ('eigengradcam', 'EigenGrad‑CAM'), ('ablationcam', 'Ablation‑CAM')], help_text='Which XAI algorithm to run (if any)', max_length=32, null=True),
        ),
    ]
