# Generated by Django 5.2.1 on 2025-08-26 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_model_model_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the machine learning model', max_length=255)),
                ('description', models.TextField(help_text='Description of the model')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of model creation')),
                ('allowed_users', models.JSONField(blank=True, default=list, help_text='List of allowed user types for this model', null=True)),
                ('created_by', models.ForeignKey(help_text='Admin who uploaded the model', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
