# Generated by Django 5.2.2 on 2025-06-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_model_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.testcase', verbose_name='Test Case'),
        ),
    ]
