# Generated by Django 5.2.2 on 2025-07-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_testcase_xai_algo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='model_image',
            new_name='model_thumbnail',
        ),
    ]
