# Generated by Django 5.2.3 on 2025-08-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0007_rename_model_image_model_model_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="predictor.model",
                verbose_name="Model Used",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="bounding_boxes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="xai_visualization",
            field=models.ImageField(
                blank=True, null=True, upload_to="xai_visualizations/"
            ),
        ),
    ]
