# Generated by Django 5.2.2 on 2025-09-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_container'),
        ('predictor', '0008_report_model_alter_report_bounding_boxes_and_more'),
    ]

    operations = [
    ]
